[package]
name = "json_parser"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
noir_sort = {tag = "v0.3.0", git = "https://github.com/noir-lang/noir_sort"}
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
