/*
{
    "name": "Adeel Solangi",
    "age": 62,
    "portfolio": {
        "vibe_ratings": [
            1, 4, 6, 89
        ],
        "elemental_lorem_ipsum": [
            {
                "flim": "flam",
                "polar": "bear",
                "watson": false
            },
            {
                "flim": "malf",
                "polar": "penguin",
                "watson": true
            }
        ]
    }
}
*/
global JSON_WITH_ARRAYS: str<433> = "\n{\n    \"name\": \"Adeel Solangi\",\n    \"age\": 62,\n    \"portfolio\": {\n        \"vibe_ratings\": [\n            1, 4, 6, 89\n        ],\n        \"elemental_lorem_ipsum\": [\n            {\n                \"flim\": \"flam\",\n                \"polar\": \"bear\",\n                \"watson\": false\n            },\n            {\n                \"flim\": \"malf\",\n                \"polar\": \"penguin\",\n                \"watson\": true\n            }\n        ]\n    }\n}\n";
