name: Benchmarks

on:
  push:
   branches:
    - main
  pull_request:

jobs:
  test:
    name: Benchmark library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: 1.0.0-beta.12

      - name: Install bb
        run: |
          curl -L https://bbup.aztec.network | bash
          ~/.bb/bbup -nv 1.0.0-beta.7
          sudo apt install libc++-dev

      - name: Build Noir benchmark programs
        run: nargo export

      - name: Generate gates report
        run: ./scripts/build-gates-report.sh
        env:
          BACKEND: /home/runner/.bb/bb

      - name: Store ACIR opcode benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "ACIR Opcodes"
          tool: "customSmallerIsBetter"
          output-file-path: "benchmark-opcodes.json"
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "dev/bench"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-always: ${{ contains( github.event.pull_request.labels.*.name, 'bench-show') }}
          comment-on-alert: true
          alert-threshold: "101%"
          fail-on-alert: false 
          max-items-in-chart: 50
      
      - name: Store gates benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Circuit Size"
          tool: "customSmallerIsBetter"
          output-file-path: "benchmark-circuit.json"
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "dev/bench"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-always: ${{ contains( github.event.pull_request.labels.*.name, 'bench-show') }}
          comment-on-alert: true
          alert-threshold: "101%"
          fail-on-alert: false 
          max-items-in-chart: 50
          skip-fetch-gh-pages: true

      # Delete the export files
      - name: Delete export files
        run: rm -rf export
      # Run nargo export again with force-brillig flag
      - name: Build Brillig benchmark programs
        run: nargo export --force-brillig

      - name: Generate brillig report
        run: ./scripts/build-brillig-report.sh

      - name: Store brillig benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Brillig Bytecode Size"
          tool: "customSmallerIsBetter"
          output-file-path: "benchmark-brillig.json"
          gh-pages-branch: "gh-pages"
          benchmark-data-dir-path: "dev/bench"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-always: ${{ contains( github.event.pull_request.labels.*.name, 'bench-show') }}
          comment-on-alert: true
          alert-threshold: "101%"
          fail-on-alert: false 
          max-items-in-chart: 50
          skip-fetch-gh-pages: true
          
